# library('data.table')
library(cathayR)
inicathayR()

# 應變數研究
# 讀取資料
ABT_CONTRACT1 <- fread('~/R/ML/CAR/CAR_ABT_GROUP1.csv', header = TRUE)[,292]
ABT_CONTRACT2 <- fread('~/R/ML/CAR/CAR_ABT_GROUP2.csv', header = TRUE)[,292]
ABT_CONTRACT3 <- fread('~/R/ML/CAR/CAR_ABT_GROUP3.csv', header = TRUE)[,292]
ABT_CONTRACT4 <- fread('~/R/ML/CAR/CAR_ABT_GROUP4.csv', header = TRUE)[,292]
ABT_CONTRACT=rbind(ABT_CONTRACT1,ABT_CONTRACT2,ABT_CONTRACT3,ABT_CONTRACT4)
ABT_CONTRACT1=as.numeric(ABT_CONTRACT1$LOSS_RATE)
ABT_CONTRACT2=as.numeric(ABT_CONTRACT2$LOSS_RATE)
ABT_CONTRACT3=as.numeric(ABT_CONTRACT3$LOSS_RATE)
ABT_CONTRACT4=as.numeric(ABT_CONTRACT4$LOSS_RATE)
ABT_CONTRACT=as.numeric(ABT_CONTRACT$LOSS_RATE)
class(ABT_CONTRACT)
name_list<-c('ABT_CONTRACT1','ABT_CONTRACT2','ABT_CONTRACT3','ABT_CONTRACT4')


# 原始資料探勘
hist(ABT_CONTRACT)
summary(ABT_CONTRACT)
# 整體平均0.4964
summary(ABT_CONTRACT1) # 平均0.380
summary(ABT_CONTRACT2) # 平均0.6067
summary(ABT_CONTRACT3) # 平均0.2515
summary(ABT_CONTRACT4) # 平均0.427

# 每個損率分檻等級需要分開做

############ GROUP1 新件 小客車 損率平均0.380 ############ 
PAYOUT_RATE=ABT_CONTRACT1
# 將0去掉
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
PAYOUT_RATE=autoTransOutlier(data.frame(PAYOUT_RATE),'PAYOUT_RATE')
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 1.83  max 6.16
PAYOUT_RATE=ABT_CONTRACT1
# 將0去掉 & <=1
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0 & PAYOUT_RATE<=1)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 0.76  

# 各區間占比
PAYOUT_RATE=ABT_CONTRACT1
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
# L 38.28% / 92.89%
sum(PAYOUT_RATE<0.76)/length(PAYOUT_RATE)
# M 27.28% / 3.14%
sum(PAYOUT_RATE>=0.76 & PAYOUT_RATE<1.83)/length(PAYOUT_RATE)
# H 34.45% / 4.0%
sum(PAYOUT_RATE>=1.83)/length(PAYOUT_RATE)


############ GROUP2 續保件 小客車 損率平均0.6067 ############ 
PAYOUT_RATE=ABT_CONTRACT2
# 將0去掉
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
PAYOUT_RATE=autoTransOutlier(data.frame(PAYOUT_RATE),'PAYOUT_RATE')
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 5.22  max 16.18
PAYOUT_RATE=ABT_CONTRACT2
# 將0去掉 & <=1
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0 & PAYOUT_RATE<=1)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 0.78  

# 各區間占比
PAYOUT_RATE=ABT_CONTRACT2
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
# L 21.23% / 92.44%
sum(PAYOUT_RATE<0.78)/length(PAYOUT_RATE)
# M 46.48% / 4.48%
sum(PAYOUT_RATE>=0.78 & PAYOUT_RATE<5.22)/length(PAYOUT_RATE)
# H 32.09% / 3.08%
sum(PAYOUT_RATE>=5.22)/length(PAYOUT_RATE)



############ GROUP3 新件 非小客車 損率平均0.2515 ############ 
PAYOUT_RATE=ABT_CONTRACT3
# 將0去掉
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
PAYOUT_RATE=autoTransOutlier(data.frame(PAYOUT_RATE),'PAYOUT_RATE')
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 1.37  max 4.83
PAYOUT_RATE=ABT_CONTRACT3
# 將0去掉 & <=1
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0 & PAYOUT_RATE<=1)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 0.71 

# 各區間占比
PAYOUT_RATE=ABT_CONTRACT3
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
# L 43.11% / 94.65%
sum(PAYOUT_RATE<0.71)/length(PAYOUT_RATE)
# M 21.60% / 2.03%
sum(PAYOUT_RATE>=0.71 & PAYOUT_RATE<1.37)/length(PAYOUT_RATE)
# H 35.28% / 3.32%
sum(PAYOUT_RATE>=1.37)/length(PAYOUT_RATE)




############ GROUP4 續保件 非小客車 損率平均0.427 ############ 
PAYOUT_RATE=ABT_CONTRACT4
# 將0去掉
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
PAYOUT_RATE=autoTransOutlier(data.frame(PAYOUT_RATE),'PAYOUT_RATE')
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 4.85  max 15.35
PAYOUT_RATE=ABT_CONTRACT4
# 將0去掉 & <=1
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0 & PAYOUT_RATE<=1)]
hist(PAYOUT_RATE)
summary(PAYOUT_RATE)
# 閥值 3Qu. 0.77

# 各區間占比
PAYOUT_RATE=ABT_CONTRACT4
PAYOUT_RATE=PAYOUT_RATE[which(PAYOUT_RATE>0)]
# L 22.41% / 94.45%
sum(PAYOUT_RATE<0.77)/length(PAYOUT_RATE)
# M 44.81% / 3.20%
sum(PAYOUT_RATE>=0.77 & PAYOUT_RATE<4.85)/length(PAYOUT_RATE)
# H 32.77% / 2.34%
sum(PAYOUT_RATE>=4.85)/length(PAYOUT_RATE)





